<?php

namespace EasyMag\OrderBundle\Repository;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommandIdByCommercial($commercial)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id')
            ->join('c.customer', 'cc')
            ->join('cc.commercial', 'ccc')
            ->where('ccc = :commercial')
            ->setParameter('commercial', $commercial)
            ->getQuery()
            ->getArrayResult()
        ;

        return $qb;
    }
}
