<?php

namespace EasyMag\OrderBundle\Repository;

/**
 * Command_ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Command_ProductRepository extends \Doctrine\ORM\EntityRepository
{
}
