<?php

namespace EasyMag\OrderBundle\Repository;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * SectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorRepository extends \Doctrine\ORM\EntityRepository
{
    public function find3LastSectorByCommercial($commercial) {
        $qb = $this->createQueryBuilder('s')
            ->where('s.commercial = :commercial')
            ->setParameter('commercial', $commercial)
            ->orderBy('s.datepublication','desc')
            ->setMaxResults(3)
            ->getQuery()
            ->getResult();
        return $qb;
    }

    public function findSectorByCommercialByYear($commercial, $year) {
        $start = $year.'-01-01';
        $end = $year.'-12-31';
        $qb = $this->createQueryBuilder('s')
            ->where('s.commercial = :commercial')
            ->andWhere('s.datepublication BETWEEN :start AND :end')
            ->setParameters(array(
                'commercial' => $commercial,
                'start' => $start,
                'end' => $end,
            ))
            ->orderBy('s.datepublication', 'desc')
            ->getQuery()
            ->getResult();
        return $qb;
    }

}
