client_index:
    path:     /
    defaults: { _controller: "EasyMagOrderBundle:Customer:index" }
    methods:  GET

client_show:
    path:     /{id}/show
    defaults: { _controller: "EasyMagOrderBundle:Customer:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "EasyMagOrderBundle:Customer:new" }
    methods:  [GET, POST]

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "EasyMagOrderBundle:Customer:edit" }
    methods:  [GET, POST]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "EasyMagOrderBundle:Customer:delete" }
    methods:  DELETE
