easy_mag_order_client:
    resource: "@EasyMagOrderBundle/Resources/config/routing_customer.yml"
    prefix:   /client

easy_mag_order_back_office_homepage:
    path:     /
    defaults: { _controller: EasyMagOrderBundle:Default:index }
