# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

services:
    app.datatable.post:
        class: EasyMag\OrderBundle\Datatables\CommandDatatable
        parent: sg_datatables.datatable.abstract

    form.type.create_document:
        class: EasyMag\OrderBundle\Form\DocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

    form.type.edit_document:
        class: EasyMag\OrderBundle\Form\DocumentType
        arguments: ['@service_container', '@session']
        tags:
            - { name: form.type }

