# ROUTES LIEES AU COMPTE COMMERCIAL
#---------------------------------

commercial_index:
    path:     /
    defaults: { _controller: EasyMagUserBundle:Commercial:index }





# ROUTES LIEES AUX CLIENTS
#-------------------------