<?php

namespace EasyMag\UserBundle\Repository;

/**
 * GraphisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphisteRepository extends \Doctrine\ORM\EntityRepository
{
}
