<?php

namespace EasyMag\UserBundle\Repository;

/**
 * SouscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
